# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unityguid < Formula
  desc "List up unity guids, detect conflict and replace guids."
  homepage "https://github.com/mattak/unityguid"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.2/unityguid_darwin_arm64.tar.gz"
      sha256 "e387447a0661fc8b2ca622482b56cf40d9b3e5cf9c0a350d3e86cadea9c81e8f"

      def install
        system "go" "build"
        bin.install "unityguid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.2/unityguid_darwin_x86_64.tar.gz"
      sha256 "664dc4430c91b55383cdeea2bdd0578c3570be0bfa1f672842b80f8099cd5946"

      def install
        system "go" "build"
        bin.install "unityguid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.2/unityguid_linux_x86_64.tar.gz"
      sha256 "9d41bef024a4b7c7315d02925deebe50dafb28572d9686d7b900d67771958b0f"

      def install
        system "go" "build"
        bin.install "unityguid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.2/unityguid_linux_arm64.tar.gz"
      sha256 "b5c030701f5d1c96b7ea89db2f6c4e8e63a5264f7cde1406abc543f51bee5eec"

      def install
        system "go" "build"
        bin.install "unityguid"
      end
    end
  end
end
