# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unityguid < Formula
  desc "List up unity guids, detect conflict and replace guids."
  homepage "https://github.com/mattak/unityguid"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.4/unityguid_darwin_arm64.tar.gz"
      sha256 "98605ed2894c19a6ae91174ab2229d81b1f48faec80f74da259ffb609ce93aa1"

      def install
        bin.install "unityguid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.4/unityguid_darwin_x86_64.tar.gz"
      sha256 "ca13d6d45393663053f14c531a60c847a83b94bc94b7e8d761c2734f4dfd4355"

      def install
        bin.install "unityguid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.4/unityguid_linux_arm64.tar.gz"
      sha256 "0c8997bd56b053c33b871e4a3ec48f1afaccec6c284b5f36ef865b522fb915a7"

      def install
        bin.install "unityguid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattak/unityguid/releases/download/v1.0.4/unityguid_linux_x86_64.tar.gz"
      sha256 "cd75cc279a7fe1964c86e8c79a621a6b2854996a29c7f73a1f9772678c9ba5e8"

      def install
        bin.install "unityguid"
      end
    end
  end
end
